project:
  type: book
  output-dir: _book

book:
  title: "SQL for Data Science"
  subtitle: "Exploring SQL and the World of Databases"
  reader-mode: true
  author: "Pete Benbow"

  page-footer:
    left: |
      _SQL for Data Science_ was written by Pete Benbow
    right: |
      This book was written with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: getting-started.qmd
      chapters:
        - 01-why-learn-sql.qmd
        - 02-installing-postgresql.qmd

    - part: querying-data.qmd
      chapters:
        - 03-select-statements.qmd
        - 04-data-types.qmd

    - part: working-with-multiple-tables.qmd
      chapters:
        - 05-joins.qmd
        - 06-set-operations.qmd

    - part: database-design.qmd
      chapters:
        - 07-keys-and-integrity.qmd
        - 08-er-diagrams.qmd
        - 09-normal-forms.qmd
        - 10-create-table.qmd

    - references.qmd

filters:
  - quarto-dbml

bibliography: references.bib

format:
  html:
    theme: materia
