<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Pete Benbow">

<title>6&nbsp; Joining Tables – SQL for Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./15-set-operations.html" rel="next">
<link href="./13-aggregating.html" rel="prev">
<link href="./cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e6a145422a7536efbb204f5a8d1c5774.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">

<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-query.html">Query</a></li><li class="breadcrumb-item"><a href="./14-joins.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Joining Tables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">SQL for Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/pebenbow/sql4ds" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./00-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-why-learn-sql.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Learn SQL?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Setup</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./10-query.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Query</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-select-statements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">SELECT Statements</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-data-types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Types</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-aggregating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Aggregating with GROUP BY</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-joins.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Joining Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-set-operations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Set Operations</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./20-analyze.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analyze</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-conditional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conditional Expressions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-subqueries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Subqueries and CTEs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-window-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Window Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-stats-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Statistical Functions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./30-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-keys-and-integrity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Keys and Referential Integrity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32-er-diagrams.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Entity-Relationship Diagrams</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33-normal-forms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Database Normalization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34-create-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Creating Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./35-views.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Views and Materialized Views</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./36-building-schema.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Building a Schema</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./37-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">User-Defined Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./38-procedures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Stored Procedures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./39-triggers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Triggers</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./40-optimize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Optimize</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41-explain.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Reading Query Plans</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42-indexes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Indexes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43-optimization-patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Query Optimization Patterns</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./50-secure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Secure</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./51-roles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Roles and Users</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./52-privileges.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Privileges</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./53-sqli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">SQL Injection</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./60-load.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Load</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./61-extracting-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Extracting Data from Files and APIs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./62-transforming-with-polars.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Transforming Data with Polars</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./63-loading-with-sqlalchemy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Loading Data into PostgreSQL with SQLAlchemy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./64-etl-pipeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">A Complete ETL Pipeline</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./70-deploy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deploy</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./71-supabase-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Getting Started with Supabase</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./72-supabase-vscode.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Deploying from VS Code</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./73-database-migrations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Database Migrations</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#keys-and-relationships" id="toc-keys-and-relationships" class="nav-link active" data-scroll-target="#keys-and-relationships"><span class="header-section-number">6.1</span> Keys and Relationships</a>
  <ul class="collapse">
  <li><a href="#primary-keys" id="toc-primary-keys" class="nav-link" data-scroll-target="#primary-keys"><span class="header-section-number">6.1.1</span> Primary Keys</a></li>
  <li><a href="#foreign-keys" id="toc-foreign-keys" class="nav-link" data-scroll-target="#foreign-keys"><span class="header-section-number">6.1.2</span> Foreign Keys</a></li>
  <li><a href="#cardinality" id="toc-cardinality" class="nav-link" data-scroll-target="#cardinality"><span class="header-section-number">6.1.3</span> Cardinality</a></li>
  </ul></li>
  <li><a href="#the-worldbank-database" id="toc-the-worldbank-database" class="nav-link" data-scroll-target="#the-worldbank-database"><span class="header-section-number">6.2</span> The worldbank Database</a></li>
  <li><a href="#join-syntax" id="toc-join-syntax" class="nav-link" data-scroll-target="#join-syntax"><span class="header-section-number">6.3</span> JOIN Syntax</a></li>
  <li><a href="#reading-the-diagrams" id="toc-reading-the-diagrams" class="nav-link" data-scroll-target="#reading-the-diagrams"><span class="header-section-number">6.4</span> Reading the Diagrams</a></li>
  <li><a href="#inner-join" id="toc-inner-join" class="nav-link" data-scroll-target="#inner-join"><span class="header-section-number">6.5</span> INNER JOIN</a></li>
  <li><a href="#left-join" id="toc-left-join" class="nav-link" data-scroll-target="#left-join"><span class="header-section-number">6.6</span> LEFT JOIN</a>
  <ul class="collapse">
  <li><a href="#on-vs.-where-when-filter-placement-matters" id="toc-on-vs.-where-when-filter-placement-matters" class="nav-link" data-scroll-target="#on-vs.-where-when-filter-placement-matters"><span class="header-section-number">6.6.1</span> ON vs.&nbsp;WHERE: When Filter Placement Matters</a></li>
  <li><a href="#right-join" id="toc-right-join" class="nav-link" data-scroll-target="#right-join"><span class="header-section-number">6.6.2</span> RIGHT JOIN</a></li>
  </ul></li>
  <li><a href="#full-outer-join" id="toc-full-outer-join" class="nav-link" data-scroll-target="#full-outer-join"><span class="header-section-number">6.7</span> FULL OUTER JOIN</a></li>
  <li><a href="#cross-join" id="toc-cross-join" class="nav-link" data-scroll-target="#cross-join"><span class="header-section-number">6.8</span> CROSS JOIN</a></li>
  <li><a href="#anti-joins" id="toc-anti-joins" class="nav-link" data-scroll-target="#anti-joins"><span class="header-section-number">6.9</span> Anti-Joins</a>
  <ul class="collapse">
  <li><a href="#using-left-join-and-is-null" id="toc-using-left-join-and-is-null" class="nav-link" data-scroll-target="#using-left-join-and-is-null"><span class="header-section-number">6.9.1</span> Using LEFT JOIN and IS NULL</a></li>
  <li><a href="#using-not-exists" id="toc-using-not-exists" class="nav-link" data-scroll-target="#using-not-exists"><span class="header-section-number">6.9.2</span> Using NOT EXISTS</a></li>
  </ul></li>
  <li><a href="#joining-more-than-two-tables" id="toc-joining-more-than-two-tables" class="nav-link" data-scroll-target="#joining-more-than-two-tables"><span class="header-section-number">6.10</span> Joining More Than Two Tables</a></li>
  <li><a href="#implicit-vs.-explicit-join-syntax" id="toc-implicit-vs.-explicit-join-syntax" class="nav-link" data-scroll-target="#implicit-vs.-explicit-join-syntax"><span class="header-section-number">6.11</span> Implicit vs.&nbsp;Explicit Join Syntax</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">6.12</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection"><span class="header-section-number">6.12.1</span> Reflection</a></li>
  <li><a href="#coding" id="toc-coding" class="nav-link" data-scroll-target="#coding"><span class="header-section-number">6.12.2</span> Coding</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/pebenbow/sql4ds/edit/main/14-joins.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/pebenbow/sql4ds/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<div class="alert alert-warning border-start border-warning border-4" role="alert">
    <div class="d-flex align-items-center">
        <i class="bi bi-exclamation-triangle-fill me-2"></i>
        <div>
            <strong>In Development:</strong> This textbook is currently
            undergoing development and should not be used as an authoritative
            source of... well, ANYTHING.
        </div>
    </div>
</div>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-query.html">Query</a></li><li class="breadcrumb-item"><a href="./14-joins.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Joining Tables</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Joining Tables</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Every query you have written so far has drawn from a single table. That is useful, but it is not the whole story. Real databases almost always store related information across multiple tables, and one of SQL’s most powerful capabilities is the ability to combine those tables into a single result. That operation is called a <strong>join</strong>.</p>
<p>This chapter explains why data is structured across multiple tables in the first place, introduces the key concepts of primary keys, foreign keys, and cardinality, and then walks through every major join type with diagrams and examples. By the end, you will be able to assemble information from several related tables into exactly the view you need.</p>
<section id="keys-and-relationships" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="keys-and-relationships"><span class="header-section-number">6.1</span> Keys and Relationships</h2>
<p>To understand joins, you first need to understand how tables are related to each other. Relational databases are built around the idea that data should be stored once and referenced many times, rather than repeated in every table that needs it. The mechanism that makes this possible is the relationship between tables, expressed through keys.</p>
<section id="primary-keys" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="primary-keys"><span class="header-section-number">6.1.1</span> Primary Keys</h3>
<p>A <strong>primary key</strong> is a column, or combination of columns, whose values uniquely identify each row in a table. No two rows in a table can share the same primary key value, and the primary key column cannot be NULL.</p>
<p>Primary keys come in two common forms:</p>
<ul>
<li><strong>Natural keys</strong> use a value that already exists in the data and is inherently unique, such as a country’s three-letter ISO code or a flight number.</li>
<li><strong>Surrogate keys</strong> are artificial values added solely to serve as identifiers, typically auto-incrementing integers (<code>1</code>, <code>2</code>, <code>3</code>, …) with no meaning outside the database.</li>
</ul>
<p>Natural keys are intuitive but can cause problems if the “unique” real-world value turns out to change or repeat. Surrogate keys are more stable, which is why they appear so frequently in production databases.</p>
<p>When no single column is sufficient to uniquely identify every row, two or more columns together can serve as the primary key. This is called a <strong>composite primary key</strong>. The <code>indicators</code> table in this chapter is a good example: neither <code>country_id</code> nor <code>year</code> is unique on its own, but the combination of the two identifies exactly one row, the measurements recorded for that country in that year.</p>
</section>
<section id="foreign-keys" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="foreign-keys"><span class="header-section-number">6.1.2</span> Foreign Keys</h3>
<p>A <strong>foreign key</strong> is a column in one table that holds values matching the primary key of another table. It is the bridge between two tables and the foundation of every join.</p>
<p>For example, the <code>indicators</code> table has a column called <code>country_id</code>, and the <code>countries</code> table has <code>id</code> as its primary key. The column <code>indicators.country_id</code> is a foreign key pointing to <code>countries.id</code>. Every value in <code>indicators.country_id</code> should correspond to a row that actually exists in <code>countries</code>. This guarantee is called <strong>referential integrity</strong>, and the database can enforce it automatically once the foreign key relationship is declared.</p>
<p>The table that holds the foreign key is called the <strong>child</strong> table. The table being referenced is the <strong>parent</strong> table. In this example, <code>indicators</code> is the child and <code>countries</code> is the parent.</p>
</section>
<section id="cardinality" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="cardinality"><span class="header-section-number">6.1.3</span> Cardinality</h3>
<p><strong>Cardinality</strong> describes how many rows in one table can relate to how many rows in another. There are three fundamental patterns.</p>
<p><strong>One-to-one.</strong> Each row in Table A corresponds to at most one row in Table B, and vice versa. This pattern is relatively rare. It sometimes appears when a large table is split in two for organizational or access-control reasons.</p>
<p><strong>One-to-many.</strong> Each row in Table A can relate to many rows in Table B, but each row in Table B relates to exactly one row in Table A. This is the most common cardinality in relational databases. One country can have many rows in <code>indicators</code>, one for each year that data was recorded. Each indicator row, in turn, belongs to exactly one country.</p>
<p><strong>Many-to-many.</strong> Each row in Table A can relate to many rows in Table B, and each row in Table B can relate to many rows in Table A. A student can be enrolled in many courses, and the same course can have many students. This relationship cannot be expressed with just two tables. It requires a third table, often called a <strong>junction table</strong> or <strong>bridge table</strong>, whose rows each pair one row from Table A with one row from Table B.</p>
<p>Understanding cardinality before writing a join is important because it tells you how many result rows to expect. Joining a parent table to a child in a one-to-many relationship will produce more rows than the parent table alone, one result row for each matching child. Forgetting this is a common source of unintentionally duplicated rows.</p>
<p>This chapter introduces primary keys, foreign keys, and cardinality as the practical foundation for writing joins. The database design section later in this book covers all three in greater depth, including how to declare and enforce them in SQL using <code>CREATE TABLE</code> statements and column constraints, and how normalization principles guide decisions about table structure.</p>
</section>
</section>
<section id="the-worldbank-database" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="the-worldbank-database"><span class="header-section-number">6.2</span> The worldbank Database</h2>
<p>The examples in this chapter use the <code>worldbank</code> database, which contains three tables drawn from World Bank development data.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Table</th>
<th>Primary Key</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>countries</code></td>
<td><code>id</code></td>
<td>One row per country or territory (299 rows)</td>
</tr>
<tr class="even">
<td><code>indicators</code></td>
<td><code>(country_id, year)</code></td>
<td>One row per country-year with multiple measurement columns (16,704 rows)</td>
</tr>
<tr class="odd">
<td><code>series</code></td>
<td><code>id</code></td>
<td>Metadata describing each measurement type (9 rows)</td>
</tr>
</tbody>
</table>
<p>The only enforced foreign key relationship is:</p>
<ul>
<li><code>indicators.country_id</code> references <code>countries.id</code></li>
</ul>
<p>The <code>countries</code> table includes both individual countries and regional aggregates such as “Africa” and “High income”. These 38 aggregate entries appear in <code>countries</code> but have no corresponding rows in <code>indicators</code>, which records data only for individual countries. That natural gap is what makes the left join and anti-join examples in this chapter meaningful.</p>
<p>The <code>indicators</code> table stores measurements as columns rather than rows. Each row captures one country in one year, and columns like <code>gdp_per_capita_usd</code>, <code>population</code>, <code>pct_forest_area</code>, and <code>land_area_km2</code> hold the values for that combination. Data spans from 1960 through 2023.</p>
<p>The <code>series</code> table describes what each measurement type means, including indicator codes, names, and source descriptions. It is not linked to <code>indicators</code> by a foreign key, but it is a useful reference when you want to understand what a particular column represents.</p>
</section>
<section id="join-syntax" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="join-syntax"><span class="header-section-number">6.3</span> JOIN Syntax</h2>
<p>Before looking at specific join types, it helps to see the general shape of a join query.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    i.gdp_per_capita_usd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="kw">JOIN</span> indicators <span class="kw">AS</span> i <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>A few things to note.</p>
<p><strong>Table aliases.</strong> The <code>AS c</code> and <code>AS i</code> after each table name assign short aliases. These are optional but almost universally used when joining tables, because they make it possible to refer to columns unambiguously without typing the full table name each time.</p>
<p><strong>Column qualification.</strong> When two tables share a column name, you must prefix the column name with the table alias to tell the database which one you mean. Writing <code>c.id</code> instead of just <code>id</code> prevents ambiguity. Even when column names do not overlap, qualifying them explicitly is good practice in join queries because it makes it immediately clear where each column originates.</p>
<p><strong>The ON clause.</strong> This is where you specify the condition that links the two tables. Almost always this is an equality between a foreign key in one table and the primary key in another, though more complex conditions are possible.</p>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>PostgreSQL also supports a <code>USING</code> clause as a shorthand when both tables share an identically named join column:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> table_a</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="kw">JOIN</span> table_b <span class="kw">USING</span> (shared_column_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>USING</code> is concise but requires the join columns to carry the same name in both tables. Because <code>countries</code> uses <code>id</code> while <code>indicators</code> uses <code>country_id</code>, this particular join must use <code>ON</code>. Throughout this book, all examples use <code>ON</code> for clarity and consistency.</p>
</div>
</div>
</div>
</section>
<section id="reading-the-diagrams" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="reading-the-diagrams"><span class="header-section-number">6.4</span> Reading the Diagrams</h2>
<p>The diagrams in this chapter use the <strong>checkered flag</strong> method to illustrate joins. Each diagram shows two tables arranged as rotated grids facing each other. Color-coded cells identify which rows from each table contribute to the result, and a result table on the right shows the output.</p>
<p>This approach is deliberately different from the Venn diagrams you may have seen elsewhere. Venn diagrams are not entirely wrong — Codd’s relational model defines a relation as an unordered set of tuples, so the set-based intuition has a legitimate foundation. The problem is more subtle. A Venn diagram implies that the “intersection” consists of rows that are identical members of both tables, the way the number 3 might belong to both Set A and Set B. A SQL join does not work that way. The two tables being joined typically contain different things entirely, and the join matches rows across them based on a condition you specify, usually a foreign key relationship. There is no literal overlap of identical elements. Venn diagrams also fail to convey cardinality: when one country joins to many yearly measurements, the result has one row per measurement, but the overlapping-circles picture gives no indication of that. The checkered flag diagrams make the row-matching process explicit, showing which rows from each table appear in the result and how NULLs fill in for unmatched rows in outer joins.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/joins-checkered-pg1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN illustrated with the checkered flag method."><img src="images/joins-checkered-pg1.png" class="img-fluid figure-img" style="width:80.0%" alt="Four checkered flag join diagrams showing the rows returned by INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN"></a></p>
<figcaption>INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN illustrated with the checkered flag method.</figcaption>
</figure>
</div>
</section>
<section id="inner-join" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="inner-join"><span class="header-section-number">6.5</span> INNER JOIN</h2>
<p>An <code>INNER JOIN</code> returns only the rows where the join condition is satisfied in <strong>both</strong> tables. Rows that have no match on the other side are excluded from the result entirely.</p>
<p>This is the default join type. Writing <code>JOIN</code> without a qualifier is equivalent to writing <code>INNER JOIN</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    c.region,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    i.gdp_per_capita_usd,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    i.population</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> i.<span class="dt">year</span> <span class="op">=</span> <span class="dv">2022</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> i.gdp_per_capita_usd <span class="kw">DESC</span> <span class="kw">NULLS</span> <span class="fu">LAST</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">10</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 37%">
<col style="width: 26%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">gdp_per_capita_usd</th>
<th style="text-align: right;">population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Monaco</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">226052.00</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Liechtenstein</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">186400.23</td>
<td style="text-align: right;">39493</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Luxembourg</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">125006.02</td>
<td style="text-align: right;">653103</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bermuda</td>
<td style="text-align: left;">North America</td>
<td style="text-align: right;">120897.31</td>
<td style="text-align: right;">64749</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Norway</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">108798.45</td>
<td style="text-align: right;">5457127</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ireland</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">106194.76</td>
<td style="text-align: right;">5165700</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">93245.80</td>
<td style="text-align: right;">8777088</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cayman Islands</td>
<td style="text-align: left;">Latin America &amp; Caribbean</td>
<td style="text-align: right;">92202.15</td>
<td style="text-align: right;">71591</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qatar</td>
<td style="text-align: left;">Middle East &amp; North Africa</td>
<td style="text-align: right;">88701.46</td>
<td style="text-align: right;">2657333</td>
</tr>
<tr class="even">
<td style="text-align: left;">Singapore</td>
<td style="text-align: left;">East Asia &amp; Pacific</td>
<td style="text-align: right;">88428.70</td>
<td style="text-align: right;">5637022</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This query pairs each country with its 2022 measurements. Because the join is inner, any country without a matching row in <code>indicators</code> is excluded from the result entirely. Notice that no entries from the <code>Aggregates</code> region appear: the 38 regional aggregates in <code>countries</code> have no rows in <code>indicators</code>, so the inner join drops them without any warning. The next section shows how a left join makes those gaps visible.</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>When a column name exists in only one of the joined tables, you can reference it without a qualifier and PostgreSQL will resolve it unambiguously. However, any column name that appears in more than one table must be qualified with the table alias, or the query will fail with an “ambiguous column” error. When in doubt, qualify every column.</p>
</div>
</div>
</div>
</section>
<section id="left-join" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="left-join"><span class="header-section-number">6.6</span> LEFT JOIN</h2>
<p>A <code>LEFT JOIN</code> (also written <code>LEFT OUTER JOIN</code>) returns <strong>all rows from the left table</strong> and the matching rows from the right table. Where no match exists in the right table, the right-side columns are filled with NULL.</p>
<p>The “left” table is the one named in the <code>FROM</code> clause. The “right” table is the one named in the <code>JOIN</code> clause.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    c.region,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    i.<span class="dt">year</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    i.population</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> c.short_name, i.<span class="dt">year</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">15</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">year</th>
<th style="text-align: right;">population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">1960</td>
<td style="text-align: right;">9035043</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">1961</td>
<td style="text-align: right;">9214083</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">1962</td>
<td style="text-align: right;">9404406</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">1963</td>
<td style="text-align: right;">9604487</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">1964</td>
<td style="text-align: right;">9814318</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">1965</td>
<td style="text-align: right;">10036008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">1966</td>
<td style="text-align: right;">10266395</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">1967</td>
<td style="text-align: right;">10505959</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">1968</td>
<td style="text-align: right;">10756922</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">1969</td>
<td style="text-align: right;">11017409</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The first rows in this result belong to regional aggregates such as “Africa” and “Africa Eastern and Southern”. They appear with NULL in both <code>year</code> and <code>population</code> because they have no rows in <code>indicators</code>. Further down, individual countries appear once per year of recorded data. The left join preserves every row from <code>countries</code>, whether or not a match exists on the right side.</p>
<p>Left joins are extremely common in analytical queries because they let you start with a complete reference list (all countries) and attach available data without discarding entries that happen to have gaps.</p>
<section id="on-vs.-where-when-filter-placement-matters" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="on-vs.-where-when-filter-placement-matters"><span class="header-section-number">6.6.1</span> ON vs.&nbsp;WHERE: When Filter Placement Matters</h3>
<p>Every join query can have two places where you restrict rows: inside the <code>ON</code> clause and inside the <code>WHERE</code> clause. Understanding the difference is one of the most important skills in SQL, because the two clauses run at different stages of query execution and produce different results with outer joins.</p>
<p>The <strong><code>ON</code> clause</strong> runs during the join itself. It controls which rows from the right table are even considered as candidates for matching against each left-table row. Rows that fail the <code>ON</code> condition are not matched, but in an outer join, the left-table row still appears in the result with NULLs on the right side.</p>
<p>The <strong><code>WHERE</code> clause</strong> runs after the join is complete. It filters the already-assembled result set. Any row that does not satisfy <code>WHERE</code> is discarded, NULLs and all.</p>
<p><strong>With INNER JOIN, the placement makes no difference.</strong> Because an inner join already discards rows with no match, there are no NULL-padded rows for a <code>WHERE</code> filter to remove. These two queries return identical results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    i.<span class="dt">year</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    i.gdp_per_capita_usd</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> i.<span class="dt">year</span> <span class="op">=</span> <span class="dv">2022</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> c.short_name</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">5</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>5 records</caption>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: right;">year</th>
<th style="text-align: right;">gdp_per_capita_usd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">357.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa Eastern and Southern</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">1628.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Africa Western and Central</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">1777.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Albania</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">6846.43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Algeria</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">4961.55</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    i.<span class="dt">year</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    i.gdp_per_capita_usd</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id <span class="kw">AND</span> i.<span class="dt">year</span> <span class="op">=</span> <span class="dv">2022</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> c.short_name</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">5</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>5 records</caption>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: right;">year</th>
<th style="text-align: right;">gdp_per_capita_usd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">357.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa Eastern and Southern</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">1628.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Africa Western and Central</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">1777.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Albania</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">6846.43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Algeria</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">4961.55</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>With LEFT JOIN (and other outer joins), the placement is critical.</strong> Suppose you want every country alongside its 2022 GDP figure, with NULL for countries that have no 2022 data. This query does not accomplish that goal:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    c.region,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    i.<span class="dt">year</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    i.gdp_per_capita_usd</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> i.<span class="dt">year</span> <span class="op">=</span> <span class="dv">2022</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> c.short_name</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">10</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<colgroup>
<col style="width: 35%">
<col style="width: 34%">
<col style="width: 6%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">year</th>
<th style="text-align: right;">gdp_per_capita_usd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">357.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa Eastern and Southern</td>
<td style="text-align: left;">Aggregates</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">1628.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Africa Western and Central</td>
<td style="text-align: left;">Aggregates</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">1777.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Albania</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">6846.43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Algeria</td>
<td style="text-align: left;">Middle East &amp; North Africa</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">4961.55</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Samoa</td>
<td style="text-align: left;">East Asia &amp; Pacific</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">18017.46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Andorra</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">42414.06</td>
</tr>
<tr class="even">
<td style="text-align: left;">Angola</td>
<td style="text-align: left;">Sub-Saharan Africa</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">2929.69</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Antigua and Barbuda</td>
<td style="text-align: left;">Latin America &amp; Caribbean</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">20117.77</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arab World</td>
<td style="text-align: left;">Aggregates</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">7658.41</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The left join runs first and correctly produces 16,742 rows: 16,704 matched rows plus 38 NULL-padded rows for the regional aggregates. Then <code>WHERE i.year = 2022</code> runs on that result and discards every row where <code>i.year</code> is NULL, which are exactly the 38 unmatched rows. The left join’s promise of “all left rows” is silently undone, and the result is identical to an inner join.</p>
<p>Moving the condition into the <code>ON</code> clause fixes it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    c.region,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    i.<span class="dt">year</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    i.gdp_per_capita_usd</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">AND</span> i.<span class="dt">year</span> <span class="op">=</span> <span class="dv">2022</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> c.short_name</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">15</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<colgroup>
<col style="width: 35%">
<col style="width: 34%">
<col style="width: 6%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">year</th>
<th style="text-align: right;">gdp_per_capita_usd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">357.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Aggregates</td>
<td style="text-align: right;">NULL</td>
<td style="text-align: right;">NULL</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Africa Eastern and Southern</td>
<td style="text-align: left;">Aggregates</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">1628.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa Western and Central</td>
<td style="text-align: left;">Aggregates</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">1777.24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Albania</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">6846.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">Algeria</td>
<td style="text-align: left;">Middle East &amp; North Africa</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">4961.55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Samoa</td>
<td style="text-align: left;">East Asia &amp; Pacific</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">18017.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">Andorra</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">42414.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Angola</td>
<td style="text-align: left;">Sub-Saharan Africa</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">2929.69</td>
</tr>
<tr class="even">
<td style="text-align: left;">Antigua and Barbuda</td>
<td style="text-align: left;">Latin America &amp; Caribbean</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">20117.77</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now the database evaluates <code>i.year = 2022</code> during the join. For each country row, it looks for a matching indicator row where both <code>country_id</code> matches and <code>year</code> equals 2022. If no such row exists, the country still appears in the result, with NULLs on the right side. All 299 rows from <code>countries</code> come through.</p>
<p>The practical rule: <strong>conditions that restrict which right-table rows qualify as a match belong in <code>ON</code>; conditions that should discard rows from the final result regardless of match status belong in <code>WHERE</code>.</strong> For inner joins the distinction is academic. For any outer join it is not.</p>
</section>
<section id="right-join" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="right-join"><span class="header-section-number">6.6.2</span> RIGHT JOIN</h3>
<p>A <code>RIGHT JOIN</code> is the mirror image of a <code>LEFT JOIN</code>. It returns all rows from the right table and the matching rows from the left, filling unmatched left-side columns with NULL.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    i.<span class="dt">year</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    i.population</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="kw">RIGHT</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> c.short_name, i.<span class="dt">year</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">10</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: right;">year</th>
<th style="text-align: right;">population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">1960</td>
<td style="text-align: right;">9035043</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">1961</td>
<td style="text-align: right;">9214083</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">1962</td>
<td style="text-align: right;">9404406</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">1963</td>
<td style="text-align: right;">9604487</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">1964</td>
<td style="text-align: right;">9814318</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">1965</td>
<td style="text-align: right;">10036008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">1966</td>
<td style="text-align: right;">10266395</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">1967</td>
<td style="text-align: right;">10505959</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">1968</td>
<td style="text-align: right;">10756922</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">1969</td>
<td style="text-align: right;">11017409</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This returns every row from <code>indicators</code>, with the country name attached from the left table. Because <code>indicators.country_id</code> is enforced as a foreign key, every indicator row already has a valid matching country, so no NULLs appear on the left side here.</p>
<p>In practice, <code>RIGHT JOIN</code> is used infrequently. Any right join can be rewritten as a left join by swapping the order of the tables, which most developers find more readable. The queries below produce identical results:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="kw">RIGHT</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> indicators <span class="kw">AS</span> i</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> countries <span class="kw">AS</span> c <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="full-outer-join" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="full-outer-join"><span class="header-section-number">6.7</span> FULL OUTER JOIN</h2>
<p>A <code>FULL OUTER JOIN</code> returns <strong>all rows from both tables</strong>. Rows that have a match are joined together. Rows from the left table with no right-side match appear with NULLs on the right. Rows from the right table with no left-side match appear with NULLs on the left.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    c.region,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    i.gdp_per_capita_usd</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="kw">FULL</span> <span class="kw">OUTER</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">AND</span> i.<span class="dt">year</span> <span class="op">=</span> <span class="dv">2022</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> c.short_name</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">20</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<colgroup>
<col style="width: 37%">
<col style="width: 36%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">gdp_per_capita_usd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">357.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Aggregates</td>
<td style="text-align: right;">NULL</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Africa Eastern and Southern</td>
<td style="text-align: left;">Aggregates</td>
<td style="text-align: right;">1628.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa Western and Central</td>
<td style="text-align: left;">Aggregates</td>
<td style="text-align: right;">1777.24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Albania</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">6846.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">Algeria</td>
<td style="text-align: left;">Middle East &amp; North Africa</td>
<td style="text-align: right;">4961.55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Samoa</td>
<td style="text-align: left;">East Asia &amp; Pacific</td>
<td style="text-align: right;">18017.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">Andorra</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">42414.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Angola</td>
<td style="text-align: left;">Sub-Saharan Africa</td>
<td style="text-align: right;">2929.69</td>
</tr>
<tr class="even">
<td style="text-align: left;">Antigua and Barbuda</td>
<td style="text-align: left;">Latin America &amp; Caribbean</td>
<td style="text-align: right;">20117.77</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Because <code>indicators.country_id</code> is enforced as a foreign key, every indicator row already has a matching country. The only unmatched rows come from the left side: the 38 aggregates in <code>countries</code> with no indicator data. The result is therefore the same as a left join with the year in the <code>ON</code> clause. Full outer joins show their full value when comparing two datasets that are not constrained to reference each other, such as two independent snapshots of the same data where either side could contain records the other does not.</p>
</section>
<section id="cross-join" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="cross-join"><span class="header-section-number">6.8</span> CROSS JOIN</h2>
<p>A <code>CROSS JOIN</code> produces the <strong>Cartesian product</strong> of two tables: every row from the left table is paired with every row from the right table. If the left table has M rows and the right table has N rows, the result has M × N rows. No join condition is specified.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/joins-checkered-pg2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="LEFT ANTI-JOIN, RIGHT ANTI-JOIN, and CROSS JOIN illustrated with the checkered flag method."><img src="images/joins-checkered-pg2.png" class="img-fluid figure-img" style="width:80.0%" alt="Three checkered flag diagrams showing LEFT ANTI-JOIN, RIGHT ANTI-JOIN, and CROSS JOIN"></a></p>
<figcaption>LEFT ANTI-JOIN, RIGHT ANTI-JOIN, and CROSS JOIN illustrated with the checkered flag method.</figcaption>
</figure>
</div>
<p>The <code>series</code> table, with its 9 rows describing each measurement type, pairs naturally with <code>countries</code> in a cross join. The result is a complete grid of every possible country-indicator combination.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    s.indicator_name</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="kw">CROSS</span> <span class="kw">JOIN</span> series <span class="kw">AS</span> s</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> c.short_name, s.indicator_name</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">15</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 74%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: left;">indicator_name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">Agricultural land (% of land area)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">Arable land (% of land area)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">Forest area (% of land area)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">GDP (current US<span class="math inline">\()                  |
|Afghanistan |GDP per capita (current US\)</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">Land area (sq. km)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">Population, total</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">Rural land area (sq. km)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">Urban land area (sq. km)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Agricultural land (% of land area)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>With 299 countries and 9 indicator types, this produces 2,691 rows. Cross joins grow very quickly.</p>
<p>Accidental cross joins are one of the most common sources of runaway queries in SQL. They happen when a join condition is missing or typo’d, causing the database to pair every row with every other row. Always verify that a <code>JOIN</code> clause has an <code>ON</code> condition unless you genuinely intend a cross join.</p>
<p>Intentional cross joins do have legitimate uses. Generating all possible combinations of two dimensions, such as every country paired with every indicator type to build a complete reporting grid with no gaps, is a situation where a cross join is exactly the right tool.</p>
</section>
<section id="anti-joins" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="anti-joins"><span class="header-section-number">6.9</span> Anti-Joins</h2>
<p>An <strong>anti-join</strong> returns rows from one table that have <strong>no matching row</strong> in the other table. It is the complement of an inner join.</p>
<p>Anti-joins do not have a dedicated keyword in SQL. They are expressed using one of two patterns.</p>
<section id="using-left-join-and-is-null" class="level3" data-number="6.9.1">
<h3 data-number="6.9.1" class="anchored" data-anchor-id="using-left-join-and-is-null"><span class="header-section-number">6.9.1</span> Using LEFT JOIN and IS NULL</h3>
<p>The most common pattern extends a left join with a <code>WHERE</code> clause that keeps only the rows where the right side produced a NULL, meaning no match was found.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    c.region</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> i.country_id <span class="kw">IS</span> <span class="kw">NULL</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: left;">region</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="even">
<td style="text-align: left;">East Asia &amp; Pacific (IBRD-only countries)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe &amp; Central Asia (IBRD-only countries)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="even">
<td style="text-align: left;">IBRD countries classified as high income</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Latin America &amp; the Caribbean (IBRD-only countries)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="even">
<td style="text-align: left;">Middle East &amp; North Africa (IBRD-only countries)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sub-Saharan Africa (IBRD-only countries)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sub-Saharan Africa (IFC classification)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">East Asia and the Pacific (IFC classification)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe and Central Asia (IFC classification)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This returns every entry in <code>countries</code> that has no rows in <code>indicators</code>. The left join brings in all countries; the <code>WHERE</code> clause discards the ones that did match, leaving only those that did not. The result is the 38 regional aggregate entries.</p>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Filter on the join key column from the right table, not a data column. The join key is guaranteed to be NULL only when no match was found. A data column could be NULL for other reasons, which would produce false positives.</p>
</div>
</div>
</div>
</section>
<section id="using-not-exists" class="level3" data-number="6.9.2">
<h3 data-number="6.9.2" class="anchored" data-anchor-id="using-not-exists"><span class="header-section-number">6.9.2</span> Using NOT EXISTS</h3>
<p>The second pattern uses <code>NOT EXISTS</code> with a correlated subquery. This is the approach mentioned in the WHERE clause chapter as the preferred alternative to <code>NOT IN</code> when NULL values may be present.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    c.region</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> <span class="kw">NOT</span> <span class="kw">EXISTS</span> (</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="dv">1</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> indicators <span class="kw">AS</span> i</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">WHERE</span> i.country_id <span class="op">=</span> c.<span class="kw">id</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: left;">region</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="even">
<td style="text-align: left;">East Asia &amp; Pacific (IBRD-only countries)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe &amp; Central Asia (IBRD-only countries)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="even">
<td style="text-align: left;">IBRD countries classified as high income</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Latin America &amp; the Caribbean (IBRD-only countries)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="even">
<td style="text-align: left;">Middle East &amp; North Africa (IBRD-only countries)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sub-Saharan Africa (IBRD-only countries)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sub-Saharan Africa (IFC classification)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">East Asia and the Pacific (IFC classification)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe and Central Asia (IFC classification)</td>
<td style="text-align: left;">Aggregates</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The subquery runs once for each row in <code>countries</code>, checking whether any matching row exists in <code>indicators</code>. If none is found, <code>NOT EXISTS</code> returns TRUE and the country is included in the result.</p>
<p>Both patterns produce the same rows. The <code>LEFT JOIN / IS NULL</code> form is often more familiar to beginners. The <code>NOT EXISTS</code> form can be faster on large tables and handles NULL values in the join key more predictably, which is why many experienced SQL writers prefer it.</p>
</section>
</section>
<section id="joining-more-than-two-tables" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="joining-more-than-two-tables"><span class="header-section-number">6.10</span> Joining More Than Two Tables</h2>
<p>Nothing limits a query to two tables. You can chain as many joins as the data requires, adding one table at a time. One particularly useful pattern is joining the same table twice under different aliases to compare values across two points in time. Here, the <code>indicators</code> table is joined twice to place 2000 and 2022 GDP figures side by side.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    c.region,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    i2000.gdp_per_capita_usd <span class="kw">AS</span> gdp_2000,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    i2022.gdp_per_capita_usd <span class="kw">AS</span> gdp_2022</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i2000</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i2000.country_id <span class="kw">AND</span> i2000.<span class="dt">year</span> <span class="op">=</span> <span class="dv">2000</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i2022</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i2022.country_id <span class="kw">AND</span> i2022.<span class="dt">year</span> <span class="op">=</span> <span class="dv">2022</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> c.region <span class="op">!=</span> <span class="st">'Aggregates'</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> c.short_name</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">10</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">gdp_2000</th>
<th style="text-align: right;">gdp_2022</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">174.93</td>
<td style="text-align: right;">357.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Albania</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">1126.68</td>
<td style="text-align: right;">6846.43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Algeria</td>
<td style="text-align: left;">Middle East &amp; North Africa</td>
<td style="text-align: right;">1772.93</td>
<td style="text-align: right;">4961.55</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Samoa</td>
<td style="text-align: left;">East Asia &amp; Pacific</td>
<td style="text-align: right;">NULL</td>
<td style="text-align: right;">18017.46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Andorra</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">21810.25</td>
<td style="text-align: right;">42414.06</td>
</tr>
<tr class="even">
<td style="text-align: left;">Angola</td>
<td style="text-align: left;">Sub-Saharan Africa</td>
<td style="text-align: right;">563.73</td>
<td style="text-align: right;">2929.69</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Antigua and Barbuda</td>
<td style="text-align: left;">Latin America &amp; Caribbean</td>
<td style="text-align: right;">12021.46</td>
<td style="text-align: right;">20117.77</td>
</tr>
<tr class="even">
<td style="text-align: left;">Argentina</td>
<td style="text-align: left;">Latin America &amp; Caribbean</td>
<td style="text-align: right;">7637.01</td>
<td style="text-align: right;">13935.68</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Armenia</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">593.45</td>
<td style="text-align: right;">6571.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aruba</td>
<td style="text-align: left;">Latin America &amp; Caribbean</td>
<td style="text-align: right;">20681.02</td>
<td style="text-align: right;">30559.53</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Each instance of the <code>indicators</code> table gets its own alias (<code>i2000</code> and <code>i2022</code>) so the query can reference columns from each independently. The year condition is placed inside the <code>ON</code> clause for each join so it participates in the matching logic rather than filtering the result after the fact.</p>
<p>Because both joins are inner, only countries with data for <strong>both</strong> 2000 and 2022 appear. Countries that were not yet sovereign in 2000, such as South Sudan (independence: 2011), are silently excluded. If you need to preserve countries that have data for only one of the two years, replace the inner joins with left joins.</p>
<p>A few practical notes on multi-table joins:</p>
<p><strong>Start from the table that drives the query.</strong> If you want one row per country, start from <code>countries</code>. If you want one row per year-measurement, start from <code>indicators</code>. The starting table sets the row grain of the result.</p>
<p><strong>Each join adds columns, not necessarily rows.</strong> A join to a parent table in a many-to-one relationship (indicators to countries) does not change the number of rows. A join to a child table in a one-to-many relationship (countries to indicators) multiplies rows. Understanding this keeps the result size predictable.</p>
<p><strong>Order joins for readability.</strong> SQL does not require joins in any particular sequence, but organizing them so that each new table connects to something already in the query makes the logic easier to follow.</p>
</section>
<section id="implicit-vs.-explicit-join-syntax" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="implicit-vs.-explicit-join-syntax"><span class="header-section-number">6.11</span> Implicit vs.&nbsp;Explicit Join Syntax</h2>
<p>SQL has two ways to join tables. The style used throughout this book is the <strong>explicit</strong> syntax, introduced in the ANSI SQL-92 standard, where the join type and condition are stated directly:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries <span class="kw">AS</span> c</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> indicators <span class="kw">AS</span> i <span class="kw">ON</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Before SQL-92, the only option was the <strong>implicit</strong> syntax: tables are comma-separated in the <code>FROM</code> clause and the join condition appears in <code>WHERE</code> alongside any other filters. The <code>AS</code> keyword for aliases is also commonly omitted in this style.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    c.short_name,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    c.region,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    i.gdp_per_capita_usd</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries c, indicators i</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> c.<span class="kw">id</span> <span class="op">=</span> i.country_id</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> i.<span class="dt">year</span> <span class="op">=</span> <span class="dv">2022</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> i.gdp_per_capita_usd <span class="kw">DESC</span> <span class="kw">NULLS</span> <span class="fu">LAST</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">10</span>;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: left;">short_name</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">gdp_per_capita_usd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Monaco</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">226052.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Liechtenstein</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">186400.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Luxembourg</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">125006.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bermuda</td>
<td style="text-align: left;">North America</td>
<td style="text-align: right;">120897.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Norway</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">108798.45</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ireland</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">106194.76</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">93245.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cayman Islands</td>
<td style="text-align: left;">Latin America &amp; Caribbean</td>
<td style="text-align: right;">92202.15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qatar</td>
<td style="text-align: left;">Middle East &amp; North Africa</td>
<td style="text-align: right;">88701.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">Singapore</td>
<td style="text-align: left;">East Asia &amp; Pacific</td>
<td style="text-align: right;">88428.70</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The result is identical to the explicit <code>INNER JOIN</code> from earlier in this chapter. Implicit joins still execute in every major SQL database and appear frequently in legacy code, older textbooks, and online examples, so you will encounter them.</p>
<p>There are three reasons to use explicit syntax for any new work.</p>
<p><strong>Join conditions and filter conditions are visually indistinguishable.</strong> In the implicit style, <code>c.id = i.country_id</code> (a join condition) and <code>i.year = 2022</code> (a data filter) both sit in <code>WHERE</code> with no structural difference between them. With explicit syntax, join conditions live in <code>ON</code> and filters live in <code>WHERE</code>, so the purpose of each clause is immediately clear.</p>
<p><strong>A missing join condition silently produces a cross join.</strong> If the condition linking the two tables is accidentally left out in the implicit style, the database returns the Cartesian product without any warning or error:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">COUNT</span>(<span class="op">*</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> countries, indicators;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4994496</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>With explicit syntax, omitting the <code>ON</code> clause is a syntax error that fails immediately rather than quietly returning millions of rows.</p>
<p><strong>Outer joins require explicit syntax.</strong> There is no comma-table equivalent of <code>LEFT JOIN</code> or <code>FULL OUTER JOIN</code>. Some databases offered proprietary workarounds (Oracle’s <code>(+)</code> operator, for example), but they were not portable and are now deprecated. Any query that needs to preserve unmatched rows must use explicit syntax.</p>
</section>
<section id="exercises" class="level2" data-number="6.12">
<h2 data-number="6.12" class="anchored" data-anchor-id="exercises"><span class="header-section-number">6.12</span> Exercises</h2>
<section id="reflection" class="level3" data-number="6.12.1">
<h3 data-number="6.12.1" class="anchored" data-anchor-id="reflection"><span class="header-section-number">6.12.1</span> Reflection</h3>
<ol type="1">
<li><p>Explain the difference between a primary key and a foreign key. Why does a database need both?</p></li>
<li><p>A data analyst runs an inner join between <code>countries</code> (299 rows) and <code>indicators</code> without filtering by year and gets back over 16,000 rows. They suspect something went wrong. Is this necessarily a problem? Explain what produces a result with many more rows than the starting table.</p></li>
<li><p>What is the difference between putting a filter condition in the <code>ON</code> clause of a left join versus putting it in the <code>WHERE</code> clause? When does the placement matter?</p></li>
<li><p>Describe two different SQL patterns that produce an anti-join. In what circumstances might you prefer one over the other?</p></li>
<li><p>You find the following query in a legacy codebase: <code>SELECT c.short_name, i.population FROM countries c, indicators i WHERE c.id = i.country_id AND i.year = 2010</code>. Rewrite it using explicit join syntax. Does the rewrite change the result?</p></li>
</ol>
</section>
<section id="coding" class="level3" data-number="6.12.2">
<h3 data-number="6.12.2" class="anchored" data-anchor-id="coding"><span class="header-section-number">6.12.2</span> Coding</h3>
<ol start="5" type="1">
<li><p>Write a query that returns the <code>short_name</code>, <code>region</code>, and 2022 <code>gdp_per_capita_usd</code> for every country that has 2022 data in the <code>indicators</code> table. Exclude regional aggregates (where <code>region = 'Aggregates'</code>). Sort by <code>gdp_per_capita_usd</code> descending, with NULLs last. Limit to 20 rows.</p></li>
<li><p>Write a query that returns every country along with its 2010 <code>gdp_per_capita_usd</code>. Countries that have no 2010 data should still appear in the result, with NULL in the GDP column. Sort by <code>short_name</code>.</p></li>
<li><p>Write a query that returns the <code>short_name</code> and <code>region</code> of every entry in <code>countries</code> that has <strong>no rows at all</strong> in the <code>indicators</code> table. Use the <code>LEFT JOIN / IS NULL</code> pattern.</p></li>
<li><p>Rewrite the query from exercise 7 using <code>NOT EXISTS</code> instead of <code>LEFT JOIN / IS NULL</code>. Confirm that both queries return the same set of entries.</p></li>
<li><p>Write a query that returns each country’s <code>short_name</code>, <code>region</code>, and GDP per capita for both 1990 and 2022 side by side. Name the GDP columns <code>gdp_1990</code> and <code>gdp_2022</code>. Include only countries that have data for both years, and exclude regional aggregates. Sort by <code>short_name</code>.</p></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sql4ds\.com\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./13-aggregating.html" class="pagination-link" aria-label="Aggregating with GROUP BY">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Aggregating with GROUP BY</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./15-set-operations.html" class="pagination-link" aria-label="Set Operations">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Set Operations</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><em>SQL for Data Science</em> was written by Pete Benbow</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/pebenbow/sql4ds/edit/main/14-joins.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/pebenbow/sql4ds/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was written with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>